import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Editor from "@monaco-editor/react";


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Editor
          defaultLanguage="markdown"
          defaultValue="# title"
          options={{
            minimap: {
              enabled: false
            }
          }}
        />
    </div>
  )
}

export default Home
